#!/bin/bash
unset ANTHROPIC_AUTH_TOKEN
export ANTHROPIC_BASE_URL="https://open.bigmodel.cn/api/anthropic"
export ANTHROPIC_API_KEY="bdc78cf3476546019386525e5eb8c756.AqjRKxD0nZwVNTjM"
cd "$(dirname "$0")"
exec node dist/index.js gateway --port 18789
